/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package com.aelos.xtext.mappingassistance.ui.tests;

import com.aelos.xtext.mappingassistance.ui.internal.MappingassistanceActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MappingAssistanceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MappingassistanceActivator.getInstance().getInjector("com.aelos.xtext.mappingassistance.MappingAssistance");
	}

}
