/**
 * generated by Xtext 2.13.0
 */
package com.aelos.xtext.mappingassistance.mappingAssistance;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistanceFactory
 * @model kind="package"
 * @generated
 */
public interface MappingAssistancePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mappingAssistance";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.aelos.com/xtext/mappingassistance/MappingAssistance";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mappingAssistance";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MappingAssistancePackage eINSTANCE = com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl.init();

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ModelImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNCTION = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.AbstractModelImpl <em>Abstract Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.AbstractModelImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getAbstractModel()
   * @generated
   */
  int ABSTRACT_MODEL = 1;

  /**
   * The number of structural features of the '<em>Abstract Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ImportImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Comp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__COMP = ABSTRACT_MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ABSTRACT_MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ComponentImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 3;

  /**
   * The feature id for the '<em><b>Inst</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__INST = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 1;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__ARG = 2;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__ARG1 = 3;

  /**
   * The feature id for the '<em><b>Methode</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__METHODE = 4;

  /**
   * The feature id for the '<em><b>Req</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__REQ = 5;

  /**
   * The feature id for the '<em><b>Map</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__MAP = 6;

  /**
   * The feature id for the '<em><b>Bind</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__BIND = 7;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.InstanceCompImpl <em>Instance Comp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.InstanceCompImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getInstanceComp()
   * @generated
   */
  int INSTANCE_COMP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCE_COMP__NAME = 0;

  /**
   * The number of structural features of the '<em>Instance Comp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTANCE_COMP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.VariableImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 6;

  /**
   * The feature id for the '<em><b>Name Var Mode</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__NAME_VAR_MODE = 0;

  /**
   * The feature id for the '<em><b>Name Var Test</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__NAME_VAR_TEST = 1;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.BindingsImpl <em>Bindings</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.BindingsImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getBindings()
   * @generated
   */
  int BINDINGS = 7;

  /**
   * The feature id for the '<em><b>Name Comp</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDINGS__NAME_COMP = 0;

  /**
   * The feature id for the '<em><b>Name Serv1</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDINGS__NAME_SERV1 = 1;

  /**
   * The feature id for the '<em><b>Name Serv2</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDINGS__NAME_SERV2 = 2;

  /**
   * The number of structural features of the '<em>Bindings</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDINGS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.RequiredServiceImpl <em>Required Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.RequiredServiceImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getRequiredService()
   * @generated
   */
  int REQUIRED_SERVICE = 8;

  /**
   * The feature id for the '<em><b>Name Var Methode</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_SERVICE__NAME_VAR_METHODE = 0;

  /**
   * The feature id for the '<em><b>Name Comp</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_SERVICE__NAME_COMP = 1;

  /**
   * The feature id for the '<em><b>Name Serv</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_SERVICE__NAME_SERV = 2;

  /**
   * The number of structural features of the '<em>Required Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_SERVICE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ServiceNameImpl <em>Service Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ServiceNameImpl
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getServiceName()
   * @generated
   */
  int SERVICE_NAME = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Service Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Type
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getType()
   * @generated
   */
  int TYPE = 10;


  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Model#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Model#getFunction()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Function();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.AbstractModel <em>Abstract Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Model</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.AbstractModel
   * @generated
   */
  EClass getAbstractModel();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Import#getComp <em>Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comp</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Import#getComp()
   * @see #getImport()
   * @generated
   */
  EReference getImport_Comp();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getInst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inst</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getInst()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Inst();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arg</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getArg()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Arg();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arg1</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getArg1()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Arg1();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getMethode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methode</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getMethode()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Methode();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getReq <em>Req</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Req</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getReq()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Req();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getMap <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Map</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getMap()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Map();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Component#getBind <em>Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bind</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Component#getBind()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Bind();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.InstanceComp <em>Instance Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instance Comp</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.InstanceComp
   * @generated
   */
  EClass getInstanceComp();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.InstanceComp#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.InstanceComp#getName()
   * @see #getInstanceComp()
   * @generated
   */
  EAttribute getInstanceComp_Name();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Variable#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Variable#getType()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Type();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Mapping#getNameVarMode <em>Name Var Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Var Mode</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Mapping#getNameVarMode()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_NameVarMode();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Mapping#getNameVarTest <em>Name Var Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Var Test</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Mapping#getNameVarTest()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_NameVarTest();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Bindings <em>Bindings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bindings</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Bindings
   * @generated
   */
  EClass getBindings();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameComp <em>Name Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Comp</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameComp()
   * @see #getBindings()
   * @generated
   */
  EReference getBindings_NameComp();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameServ1 <em>Name Serv1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Serv1</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameServ1()
   * @see #getBindings()
   * @generated
   */
  EReference getBindings_NameServ1();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameServ2 <em>Name Serv2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Serv2</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Bindings#getNameServ2()
   * @see #getBindings()
   * @generated
   */
  EReference getBindings_NameServ2();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService <em>Required Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Required Service</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService
   * @generated
   */
  EClass getRequiredService();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameVarMethode <em>Name Var Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Name Var Methode</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameVarMethode()
   * @see #getRequiredService()
   * @generated
   */
  EReference getRequiredService_NameVarMethode();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameComp <em>Name Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Comp</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameComp()
   * @see #getRequiredService()
   * @generated
   */
  EReference getRequiredService_NameComp();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameServ <em>Name Serv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Name Serv</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.RequiredService#getNameServ()
   * @see #getRequiredService()
   * @generated
   */
  EReference getRequiredService_NameServ();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.mappingassistance.mappingAssistance.ServiceName <em>Service Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service Name</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.ServiceName
   * @generated
   */
  EClass getServiceName();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.mappingassistance.mappingAssistance.ServiceName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.ServiceName#getName()
   * @see #getServiceName()
   * @generated
   */
  EAttribute getServiceName_Name();

  /**
   * Returns the meta object for enum '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MappingAssistanceFactory getMappingAssistanceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ModelImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNCTION = eINSTANCE.getModel_Function();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.AbstractModelImpl <em>Abstract Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.AbstractModelImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getAbstractModel()
     * @generated
     */
    EClass ABSTRACT_MODEL = eINSTANCE.getAbstractModel();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ImportImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Comp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT__COMP = eINSTANCE.getImport_Comp();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ComponentImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Inst</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__INST = eINSTANCE.getComponent_Inst();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__ARG = eINSTANCE.getComponent_Arg();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__ARG1 = eINSTANCE.getComponent_Arg1();

    /**
     * The meta object literal for the '<em><b>Methode</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__METHODE = eINSTANCE.getComponent_Methode();

    /**
     * The meta object literal for the '<em><b>Req</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__REQ = eINSTANCE.getComponent_Req();

    /**
     * The meta object literal for the '<em><b>Map</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__MAP = eINSTANCE.getComponent_Map();

    /**
     * The meta object literal for the '<em><b>Bind</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__BIND = eINSTANCE.getComponent_Bind();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.InstanceCompImpl <em>Instance Comp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.InstanceCompImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getInstanceComp()
     * @generated
     */
    EClass INSTANCE_COMP = eINSTANCE.getInstanceComp();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTANCE_COMP__NAME = eINSTANCE.getInstanceComp_Name();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.VariableImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__TYPE = eINSTANCE.getVariable_Type();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Name Var Mode</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__NAME_VAR_MODE = eINSTANCE.getMapping_NameVarMode();

    /**
     * The meta object literal for the '<em><b>Name Var Test</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__NAME_VAR_TEST = eINSTANCE.getMapping_NameVarTest();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.BindingsImpl <em>Bindings</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.BindingsImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getBindings()
     * @generated
     */
    EClass BINDINGS = eINSTANCE.getBindings();

    /**
     * The meta object literal for the '<em><b>Name Comp</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDINGS__NAME_COMP = eINSTANCE.getBindings_NameComp();

    /**
     * The meta object literal for the '<em><b>Name Serv1</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDINGS__NAME_SERV1 = eINSTANCE.getBindings_NameServ1();

    /**
     * The meta object literal for the '<em><b>Name Serv2</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDINGS__NAME_SERV2 = eINSTANCE.getBindings_NameServ2();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.RequiredServiceImpl <em>Required Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.RequiredServiceImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getRequiredService()
     * @generated
     */
    EClass REQUIRED_SERVICE = eINSTANCE.getRequiredService();

    /**
     * The meta object literal for the '<em><b>Name Var Methode</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRED_SERVICE__NAME_VAR_METHODE = eINSTANCE.getRequiredService_NameVarMethode();

    /**
     * The meta object literal for the '<em><b>Name Comp</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRED_SERVICE__NAME_COMP = eINSTANCE.getRequiredService_NameComp();

    /**
     * The meta object literal for the '<em><b>Name Serv</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRED_SERVICE__NAME_SERV = eINSTANCE.getRequiredService_NameServ();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.impl.ServiceNameImpl <em>Service Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.ServiceNameImpl
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getServiceName()
     * @generated
     */
    EClass SERVICE_NAME = eINSTANCE.getServiceName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE_NAME__NAME = eINSTANCE.getServiceName_Name();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.mappingassistance.mappingAssistance.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.Type
     * @see com.aelos.xtext.mappingassistance.mappingAssistance.impl.MappingAssistancePackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

  }

} //MappingAssistancePackage
