/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package com.aelos.xtext.mappingassistance.mappingAssistance;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Driver</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aelos.xtext.mappingassistance.mappingAssistance.TestDriver#getOutVar <em>Out Var</em>}</li>
 *   <li>{@link com.aelos.xtext.mappingassistance.mappingAssistance.TestDriver#getTestOp <em>Test Op</em>}</li>
 * </ul>
 *
 * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestDriver()
 * @model
 * @generated
 */
public interface TestDriver extends EObject
{
  /**
   * Returns the value of the '<em><b>Out Var</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out Var</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out Var</em>' reference list.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestDriver_OutVar()
   * @model
   * @generated
   */
  EList<EObject> getOutVar();

  /**
   * Returns the value of the '<em><b>Test Op</b></em>' containment reference list.
   * The list contents are of type {@link com.aelos.xtext.mappingassistance.mappingAssistance.TestOP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Test Op</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Op</em>' containment reference list.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestDriver_TestOp()
   * @model containment="true"
   * @generated
   */
  EList<TestOP> getTestOp();

} // TestDriver
