/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package com.aelos.xtext.mappingassistance.mappingAssistance;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Testedservice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aelos.xtext.mappingassistance.mappingAssistance.Testedservice#getNameComp <em>Name Comp</em>}</li>
 *   <li>{@link com.aelos.xtext.mappingassistance.mappingAssistance.Testedservice#getNameServ1 <em>Name Serv1</em>}</li>
 * </ul>
 *
 * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestedservice()
 * @model
 * @generated
 */
public interface Testedservice extends EObject
{
  /**
   * Returns the value of the '<em><b>Name Comp</b></em>' reference list.
   * The list contents are of type {@link com.aelos.xtext.mappingassistance.mappingAssistance.InstanceComp}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Comp</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Comp</em>' reference list.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestedservice_NameComp()
   * @model
   * @generated
   */
  EList<InstanceComp> getNameComp();

  /**
   * Returns the value of the '<em><b>Name Serv1</b></em>' reference list.
   * The list contents are of type {@link com.aelos.xtext.mappingassistance.mappingAssistance.ServiceName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Serv1</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Serv1</em>' reference list.
   * @see com.aelos.xtext.mappingassistance.mappingAssistance.MappingAssistancePackage#getTestedservice_NameServ1()
   * @model
   * @generated
   */
  EList<ServiceName> getNameServ1();

} // Testedservice
