/**
 * generated by Xtext 2.13.0
 */
package com.aelos.xtext.testintentionsassistance.testintentionsAssistance;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getOut <em>Out</em>}</li>
 *   <li>{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getMethode <em>Methode</em>}</li>
 *   <li>{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg <em>Arg</em>}</li>
 *   <li>{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg1 <em>Arg1</em>}</li>
 * </ul>
 *
 * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistancePackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out</em>' containment reference.
   * @see #setOut(Variable)
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistancePackage#getFunction_Out()
   * @model containment="true"
   * @generated
   */
  Variable getOut();

  /**
   * Sets the value of the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getOut <em>Out</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out</em>' containment reference.
   * @see #getOut()
   * @generated
   */
  void setOut(Variable value);

  /**
   * Returns the value of the '<em><b>Methode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methode</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methode</em>' attribute.
   * @see #setMethode(String)
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistancePackage#getFunction_Methode()
   * @model
   * @generated
   */
  String getMethode();

  /**
   * Sets the value of the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getMethode <em>Methode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Methode</em>' attribute.
   * @see #getMethode()
   * @generated
   */
  void setMethode(String value);

  /**
   * Returns the value of the '<em><b>Arg</b></em>' reference list.
   * The list contents are of type {@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' reference list.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistancePackage#getFunction_Arg()
   * @model
   * @generated
   */
  EList<Variable> getArg();

  /**
   * Returns the value of the '<em><b>Arg1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arg1</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg1</em>' reference.
   * @see #setArg1(Variable)
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistancePackage#getFunction_Arg1()
   * @model
   * @generated
   */
  Variable getArg1();

  /**
   * Sets the value of the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg1 <em>Arg1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg1</em>' reference.
   * @see #getArg1()
   * @generated
   */
  void setArg1(Variable value);

} // Function
