/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package com.aelos.xtext.testintentionsassistance.testintentionsAssistance;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestintentionsAssistanceFactory
 * @model kind="package"
 * @generated
 */
public interface TestintentionsAssistancePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "testintentionsAssistance";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.aelos.com/xtext/testintentionsassistance/TestintentionsAssistance";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "testintentionsAssistance";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestintentionsAssistancePackage eINSTANCE = com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl.init();

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ModelImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AbstractElementImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 3;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DomainDeclarationImpl <em>Domain Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DomainDeclarationImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getDomainDeclaration()
   * @generated
   */
  int DOMAIN_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_DECLARATION__ELEMENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Domain Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ImportImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.FunctionImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 4;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__OUT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Methode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__METHODE = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Arg</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__ARG = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Arg1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__ARG1 = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DataImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getData()
   * @generated
   */
  int DATA = 5;

  /**
   * The feature id for the '<em><b>Inst</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__INST = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.InstImpl <em>Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.InstImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getInst()
   * @generated
   */
  int INST = 6;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST__VARIABLE = 0;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST__VALEUR = 1;

  /**
   * The number of structural features of the '<em>Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestIntentionImpl <em>Test Intention</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestIntentionImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getTestIntention()
   * @generated
   */
  int TEST_INTENTION = 7;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_INTENTION__DESCRIPTION = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_INTENTION__EXPRESSION = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Test Intention</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_INTENTION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ExpressionImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 8;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.OrImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getOr()
   * @generated
   */
  int OR = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AndImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getAnd()
   * @generated
   */
  int AND = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.EqualityImpl <em>Equality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.EqualityImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getEquality()
   * @generated
   */
  int EQUALITY = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ComparisonImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.PlusImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getPlus()
   * @generated
   */
  int PLUS = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MinusImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getMinus()
   * @generated
   */
  int MINUS = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MulOrDivImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getMulOrDiv()
   * @generated
   */
  int MUL_OR_DIV = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mul Or Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUL_OR_DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.NotImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getNot()
   * @generated
   */
  int NOT = 17;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPRESSION = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.INTImpl <em>INT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.INTImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getINT()
   * @generated
   */
  int INT = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>INT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.STRINGImpl <em>STRING</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.STRINGImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getSTRING()
   * @generated
   */
  int STRING = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>STRING</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.BooleanImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DoubleImpl <em>Double</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DoubleImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getDouble()
   * @generated
   */
  int DOUBLE = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Double</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableRefImpl <em>Variable Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableRefImpl
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getVariableRef()
   * @generated
   */
  int VARIABLE_REF = 22;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF__VARIABLE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getType()
   * @generated
   */
  int TYPE = 23;


  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration <em>Domain Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Declaration</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration
   * @generated
   */
  EClass getDomainDeclaration();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration#getName()
   * @see #getDomainDeclaration()
   * @generated
   */
  EAttribute getDomainDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.DomainDeclaration#getElements()
   * @see #getDomainDeclaration()
   * @generated
   */
  EReference getDomainDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getOut()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Out();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getMethode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Methode</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getMethode()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Methode();

  /**
   * Returns the meta object for the reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Arg</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Arg();

  /**
   * Returns the meta object for the reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg1 <em>Arg1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Arg1</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Function#getArg1()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Arg1();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Data#getInst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inst</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Data#getInst()
   * @see #getData()
   * @generated
   */
  EReference getData_Inst();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inst</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst
   * @generated
   */
  EClass getInst();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst#getVariable()
   * @see #getInst()
   * @generated
   */
  EReference getInst_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Valeur</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Inst#getValeur()
   * @see #getInst()
   * @generated
   */
  EReference getInst_Valeur();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention <em>Test Intention</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Intention</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention
   * @generated
   */
  EClass getTestIntention();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention#getDescription()
   * @see #getTestIntention()
   * @generated
   */
  EAttribute getTestIntention_Description();

  /**
   * Returns the meta object for the containment reference list '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.TestIntention#getExpression()
   * @see #getTestIntention()
   * @generated
   */
  EReference getTestIntention_Expression();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Variable#getType()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Type();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality <em>Equality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality
   * @generated
   */
  EClass getEquality();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getLeft()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Left();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getOp()
   * @see #getEquality()
   * @generated
   */
  EAttribute getEquality_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Equality#getRight()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getLeft()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Left();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getOp()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Comparison#getRight()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv <em>Mul Or Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mul Or Div</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv
   * @generated
   */
  EClass getMulOrDiv();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getLeft()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Left();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getOp()
   * @see #getMulOrDiv()
   * @generated
   */
  EAttribute getMulOrDiv_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.MulOrDiv#getRight()
   * @see #getMulOrDiv()
   * @generated
   */
  EReference getMulOrDiv_Right();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Not#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Not#getExpression()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expression();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.INT <em>INT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INT</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.INT
   * @generated
   */
  EClass getINT();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.INT#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.INT#getValue()
   * @see #getINT()
   * @generated
   */
  EAttribute getINT_Value();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.STRING <em>STRING</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>STRING</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.STRING
   * @generated
   */
  EClass getSTRING();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.STRING#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.STRING#getValue()
   * @see #getSTRING()
   * @generated
   */
  EAttribute getSTRING_Value();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Boolean#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Boolean#getValue()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Value();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Double <em>Double</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Double
   * @generated
   */
  EClass getDouble();

  /**
   * Returns the meta object for the attribute '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Double#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Double#getValue()
   * @see #getDouble()
   * @generated
   */
  EAttribute getDouble_Value();

  /**
   * Returns the meta object for class '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.VariableRef <em>Variable Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Ref</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.VariableRef
   * @generated
   */
  EClass getVariableRef();

  /**
   * Returns the meta object for the reference '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.VariableRef#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.VariableRef#getVariable()
   * @see #getVariableRef()
   * @generated
   */
  EReference getVariableRef_Variable();

  /**
   * Returns the meta object for enum '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TestintentionsAssistanceFactory getTestintentionsAssistanceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ModelImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DomainDeclarationImpl <em>Domain Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DomainDeclarationImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getDomainDeclaration()
     * @generated
     */
    EClass DOMAIN_DECLARATION = eINSTANCE.getDomainDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_DECLARATION__NAME = eINSTANCE.getDomainDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_DECLARATION__ELEMENTS = eINSTANCE.getDomainDeclaration_Elements();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ImportImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AbstractElementImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.FunctionImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__OUT = eINSTANCE.getFunction_Out();

    /**
     * The meta object literal for the '<em><b>Methode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__METHODE = eINSTANCE.getFunction_Methode();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__ARG = eINSTANCE.getFunction_Arg();

    /**
     * The meta object literal for the '<em><b>Arg1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__ARG1 = eINSTANCE.getFunction_Arg1();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DataImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Inst</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA__INST = eINSTANCE.getData_Inst();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.InstImpl <em>Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.InstImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getInst()
     * @generated
     */
    EClass INST = eINSTANCE.getInst();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INST__VARIABLE = eINSTANCE.getInst_Variable();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INST__VALEUR = eINSTANCE.getInst_Valeur();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestIntentionImpl <em>Test Intention</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestIntentionImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getTestIntention()
     * @generated
     */
    EClass TEST_INTENTION = eINSTANCE.getTestIntention();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_INTENTION__DESCRIPTION = eINSTANCE.getTestIntention_Description();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_INTENTION__EXPRESSION = eINSTANCE.getTestIntention_Expression();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ExpressionImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__TYPE = eINSTANCE.getVariable_Type();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.OrImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.AndImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.EqualityImpl <em>Equality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.EqualityImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getEquality()
     * @generated
     */
    EClass EQUALITY = eINSTANCE.getEquality();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__LEFT = eINSTANCE.getEquality_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUALITY__OP = eINSTANCE.getEquality_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__RIGHT = eINSTANCE.getEquality_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.ComparisonImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__LEFT = eINSTANCE.getComparison_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OP = eINSTANCE.getComparison_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__RIGHT = eINSTANCE.getComparison_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.PlusImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MinusImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MulOrDivImpl <em>Mul Or Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.MulOrDivImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getMulOrDiv()
     * @generated
     */
    EClass MUL_OR_DIV = eINSTANCE.getMulOrDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__LEFT = eINSTANCE.getMulOrDiv_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MUL_OR_DIV__OP = eINSTANCE.getMulOrDiv_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUL_OR_DIV__RIGHT = eINSTANCE.getMulOrDiv_Right();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.NotImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPRESSION = eINSTANCE.getNot_Expression();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.INTImpl <em>INT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.INTImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getINT()
     * @generated
     */
    EClass INT = eINSTANCE.getINT();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT__VALUE = eINSTANCE.getINT_Value();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.STRINGImpl <em>STRING</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.STRINGImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getSTRING()
     * @generated
     */
    EClass STRING = eINSTANCE.getSTRING();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING__VALUE = eINSTANCE.getSTRING_Value();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.BooleanImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VALUE = eINSTANCE.getBoolean_Value();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DoubleImpl <em>Double</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.DoubleImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getDouble()
     * @generated
     */
    EClass DOUBLE = eINSTANCE.getDouble();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOUBLE__VALUE = eINSTANCE.getDouble_Value();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableRefImpl <em>Variable Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.VariableRefImpl
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getVariableRef()
     * @generated
     */
    EClass VARIABLE_REF = eINSTANCE.getVariableRef();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_REF__VARIABLE = eINSTANCE.getVariableRef_Variable();

    /**
     * The meta object literal for the '{@link com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.Type
     * @see com.aelos.xtext.testintentionsassistance.testintentionsAssistance.impl.TestintentionsAssistancePackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

  }

} //TestintentionsAssistancePackage
