/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package com.aelos.xtext.architecture.architecture;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atomic Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.aelos.xtext.architecture.architecture.AtomicType#getAtomType <em>Atom Type</em>}</li>
 * </ul>
 *
 * @see com.aelos.xtext.architecture.architecture.ArchitecturePackage#getAtomicType()
 * @model
 * @generated
 */
public interface AtomicType extends EObject
{
  /**
   * Returns the value of the '<em><b>Atom Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.aelos.xtext.architecture.architecture.Type}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atom Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atom Type</em>' attribute.
   * @see com.aelos.xtext.architecture.architecture.Type
   * @see #setAtomType(Type)
   * @see com.aelos.xtext.architecture.architecture.ArchitecturePackage#getAtomicType_AtomType()
   * @model
   * @generated
   */
  Type getAtomType();

  /**
   * Sets the value of the '{@link com.aelos.xtext.architecture.architecture.AtomicType#getAtomType <em>Atom Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atom Type</em>' attribute.
   * @see com.aelos.xtext.architecture.architecture.Type
   * @see #getAtomType()
   * @generated
   */
  void setAtomType(Type value);

} // AtomicType
