/*
 * generated by Xtext 2.13.0
 */
package com.aelos.xtext.mappingassistance.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MappingAssistanceGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Model");
		private final Assignment cFunctionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFunctionAbstractModelParserRuleCall_0 = (RuleCall)cFunctionAssignment.eContents().get(0);
		
		//Model:
		//	function+=AbstractModel*;
		@Override public ParserRule getRule() { return rule; }
		
		//function+=AbstractModel*
		public Assignment getFunctionAssignment() { return cFunctionAssignment; }
		
		//AbstractModel
		public RuleCall getFunctionAbstractModelParserRuleCall_0() { return cFunctionAbstractModelParserRuleCall_0; }
	}
	public class AbstractModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.AbstractModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cImportParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cCompAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCompComponentParserRuleCall_1_0 = (RuleCall)cCompAssignment_1.eContents().get(0);
		
		//AbstractModel:
		//	Import comp+=Component+;
		@Override public ParserRule getRule() { return rule; }
		
		//Import comp+=Component+
		public Group getGroup() { return cGroup; }
		
		//Import
		public RuleCall getImportParserRuleCall_0() { return cImportParserRuleCall_0; }
		
		//comp+=Component+
		public Assignment getCompAssignment_1() { return cCompAssignment_1; }
		
		//Component
		public RuleCall getCompComponentParserRuleCall_1_0() { return cCompComponentParserRuleCall_1_0; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//	'import' importedNamespace=QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }
		
		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}
	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }
		
		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }
		
		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cComponentKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cMockKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cObservatorKeyword_0_2 = (Keyword)cAlternatives_0.eContents().get(2);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInstAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstInstanceCompParserRuleCall_2_0 = (RuleCall)cInstAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cProvidedServicesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cConfKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cArgAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cArgVariableParserRuleCall_7_0_0 = (RuleCall)cArgAssignment_7_0.eContents().get(0);
		private final Keyword cCommaKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cArg1Assignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cArg1VariableParserRuleCall_8_0 = (RuleCall)cArg1Assignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cMethodeAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final RuleCall cMethodeServiceNameParserRuleCall_10_0_0 = (RuleCall)cMethodeAssignment_10_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Group cGroup_10_2_0 = (Group)cGroup_10_2.eContents().get(0);
		private final Assignment cArgAssignment_10_2_0_0 = (Assignment)cGroup_10_2_0.eContents().get(0);
		private final RuleCall cArgVariableParserRuleCall_10_2_0_0_0 = (RuleCall)cArgAssignment_10_2_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_10_2_0_1 = (Keyword)cGroup_10_2_0.eContents().get(1);
		private final Assignment cArgAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final RuleCall cArgVariableParserRuleCall_10_2_1_0 = (RuleCall)cArgAssignment_10_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Group cGroup_10_4 = (Group)cGroup_10.eContents().get(4);
		private final Keyword cColonKeyword_10_4_0 = (Keyword)cGroup_10_4.eContents().get(0);
		private final Assignment cArgAssignment_10_4_1 = (Assignment)cGroup_10_4.eContents().get(1);
		private final RuleCall cArgVariableParserRuleCall_10_4_1_0 = (RuleCall)cArgAssignment_10_4_1.eContents().get(0);
		private final Keyword cRequiredServicesKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cReqAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cReqRequiredServiceParserRuleCall_12_0 = (RuleCall)cReqAssignment_12.eContents().get(0);
		private final Assignment cMapAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cMapMappingParserRuleCall_13_0 = (RuleCall)cMapAssignment_13.eContents().get(0);
		private final Assignment cBindAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cBindBindingsParserRuleCall_14_0 = (RuleCall)cBindAssignment_14.eContents().get(0);
		
		//Component:
		//	("Component" | "Mock" | "Observator") ":"
		//	inst+=InstanceComp ":" name=ID
		//	"ProvidedServices:"
		//	"conf(" (arg+=Variable ",")* arg1+=Variable ")" (methode+=ServiceName "(" ((arg+=Variable ",")* arg+=Variable)* ")"
		//	(":" arg+=Variable)?)*
		//	"RequiredServices:"?
		//	req+=RequiredService*
		//	map+=Mapping*
		//	bind+=Bindings*;
		@Override public ParserRule getRule() { return rule; }
		
		//("Component" | "Mock" | "Observator") ":" inst+=InstanceComp ":" name=ID "ProvidedServices:" "conf(" (arg+=Variable
		//",")* arg1+=Variable ")" (methode+=ServiceName "(" ((arg+=Variable ",")* arg+=Variable)* ")" (":" arg+=Variable)?)*
		//"RequiredServices:"? req+=RequiredService* map+=Mapping* bind+=Bindings*
		public Group getGroup() { return cGroup; }
		
		//"Component" | "Mock" | "Observator"
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//"Component"
		public Keyword getComponentKeyword_0_0() { return cComponentKeyword_0_0; }
		
		//"Mock"
		public Keyword getMockKeyword_0_1() { return cMockKeyword_0_1; }
		
		//"Observator"
		public Keyword getObservatorKeyword_0_2() { return cObservatorKeyword_0_2; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//inst+=InstanceComp
		public Assignment getInstAssignment_2() { return cInstAssignment_2; }
		
		//InstanceComp
		public RuleCall getInstInstanceCompParserRuleCall_2_0() { return cInstInstanceCompParserRuleCall_2_0; }
		
		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//"ProvidedServices:"
		public Keyword getProvidedServicesKeyword_5() { return cProvidedServicesKeyword_5; }
		
		//"conf("
		public Keyword getConfKeyword_6() { return cConfKeyword_6; }
		
		//(arg+=Variable ",")*
		public Group getGroup_7() { return cGroup_7; }
		
		//arg+=Variable
		public Assignment getArgAssignment_7_0() { return cArgAssignment_7_0; }
		
		//Variable
		public RuleCall getArgVariableParserRuleCall_7_0_0() { return cArgVariableParserRuleCall_7_0_0; }
		
		//","
		public Keyword getCommaKeyword_7_1() { return cCommaKeyword_7_1; }
		
		//arg1+=Variable
		public Assignment getArg1Assignment_8() { return cArg1Assignment_8; }
		
		//Variable
		public RuleCall getArg1VariableParserRuleCall_8_0() { return cArg1VariableParserRuleCall_8_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
		
		//(methode+=ServiceName "(" ((arg+=Variable ",")* arg+=Variable)* ")" (":" arg+=Variable)?)*
		public Group getGroup_10() { return cGroup_10; }
		
		//methode+=ServiceName
		public Assignment getMethodeAssignment_10_0() { return cMethodeAssignment_10_0; }
		
		//ServiceName
		public RuleCall getMethodeServiceNameParserRuleCall_10_0_0() { return cMethodeServiceNameParserRuleCall_10_0_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_10_1() { return cLeftParenthesisKeyword_10_1; }
		
		//((arg+=Variable ",")* arg+=Variable)*
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//(arg+=Variable ",")*
		public Group getGroup_10_2_0() { return cGroup_10_2_0; }
		
		//arg+=Variable
		public Assignment getArgAssignment_10_2_0_0() { return cArgAssignment_10_2_0_0; }
		
		//Variable
		public RuleCall getArgVariableParserRuleCall_10_2_0_0_0() { return cArgVariableParserRuleCall_10_2_0_0_0; }
		
		//","
		public Keyword getCommaKeyword_10_2_0_1() { return cCommaKeyword_10_2_0_1; }
		
		//arg+=Variable
		public Assignment getArgAssignment_10_2_1() { return cArgAssignment_10_2_1; }
		
		//Variable
		public RuleCall getArgVariableParserRuleCall_10_2_1_0() { return cArgVariableParserRuleCall_10_2_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_10_3() { return cRightParenthesisKeyword_10_3; }
		
		//(":" arg+=Variable)?
		public Group getGroup_10_4() { return cGroup_10_4; }
		
		//":"
		public Keyword getColonKeyword_10_4_0() { return cColonKeyword_10_4_0; }
		
		//arg+=Variable
		public Assignment getArgAssignment_10_4_1() { return cArgAssignment_10_4_1; }
		
		//Variable
		public RuleCall getArgVariableParserRuleCall_10_4_1_0() { return cArgVariableParserRuleCall_10_4_1_0; }
		
		//"RequiredServices:"?
		public Keyword getRequiredServicesKeyword_11() { return cRequiredServicesKeyword_11; }
		
		//req+=RequiredService*
		public Assignment getReqAssignment_12() { return cReqAssignment_12; }
		
		//RequiredService
		public RuleCall getReqRequiredServiceParserRuleCall_12_0() { return cReqRequiredServiceParserRuleCall_12_0; }
		
		//map+=Mapping*
		public Assignment getMapAssignment_13() { return cMapAssignment_13; }
		
		//Mapping
		public RuleCall getMapMappingParserRuleCall_13_0() { return cMapMappingParserRuleCall_13_0; }
		
		//bind+=Bindings*
		public Assignment getBindAssignment_14() { return cBindAssignment_14; }
		
		//Bindings
		public RuleCall getBindBindingsParserRuleCall_14_0() { return cBindBindingsParserRuleCall_14_0; }
	}
	public class InstanceCompElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.InstanceComp");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//InstanceComp:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeTypeEnumRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Variable:
		//	name=ID ":" type=Type;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ":" type=Type
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=Type
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_2_0() { return cTypeTypeEnumRuleCall_2_0; }
	}
	public class MappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Mapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameVarModeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNameVarModeVariableCrossReference_1_0 = (CrossReference)cNameVarModeAssignment_1.eContents().get(0);
		private final RuleCall cNameVarModeVariableIDTerminalRuleCall_1_0_1 = (RuleCall)cNameVarModeVariableCrossReference_1_0.eContents().get(1);
		private final Keyword cRefKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cVarTestKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameVarTestAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cNameVarTestVariableCrossReference_4_0 = (CrossReference)cNameVarTestAssignment_4.eContents().get(0);
		private final RuleCall cNameVarTestVariableIDTerminalRuleCall_4_0_1 = (RuleCall)cNameVarTestVariableCrossReference_4_0.eContents().get(1);
		
		//Mapping:
		//	'varModel:' nameVarMode+=[Variable] 'ref' 'varTest:' nameVarTest+=[testIntention::Variable];
		@Override public ParserRule getRule() { return rule; }
		
		//'varModel:' nameVarMode+=[Variable] 'ref' 'varTest:' nameVarTest+=[testIntention::Variable]
		public Group getGroup() { return cGroup; }
		
		//'varModel:'
		public Keyword getVarModelKeyword_0() { return cVarModelKeyword_0; }
		
		//nameVarMode+=[Variable]
		public Assignment getNameVarModeAssignment_1() { return cNameVarModeAssignment_1; }
		
		//[Variable]
		public CrossReference getNameVarModeVariableCrossReference_1_0() { return cNameVarModeVariableCrossReference_1_0; }
		
		//ID
		public RuleCall getNameVarModeVariableIDTerminalRuleCall_1_0_1() { return cNameVarModeVariableIDTerminalRuleCall_1_0_1; }
		
		//'ref'
		public Keyword getRefKeyword_2() { return cRefKeyword_2; }
		
		//'varTest:'
		public Keyword getVarTestKeyword_3() { return cVarTestKeyword_3; }
		
		//nameVarTest+=[testIntention::Variable]
		public Assignment getNameVarTestAssignment_4() { return cNameVarTestAssignment_4; }
		
		//[testIntention::Variable]
		public CrossReference getNameVarTestVariableCrossReference_4_0() { return cNameVarTestVariableCrossReference_4_0; }
		
		//ID
		public RuleCall getNameVarTestVariableIDTerminalRuleCall_4_0_1() { return cNameVarTestVariableIDTerminalRuleCall_4_0_1; }
	}
	public class BindingsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Bindings");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBindKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameCompAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNameCompInstanceCompCrossReference_1_0 = (CrossReference)cNameCompAssignment_1.eContents().get(0);
		private final RuleCall cNameCompInstanceCompIDTerminalRuleCall_1_0_1 = (RuleCall)cNameCompInstanceCompCrossReference_1_0.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameServ1Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cNameServ1ServiceNameCrossReference_3_0 = (CrossReference)cNameServ1Assignment_3.eContents().get(0);
		private final RuleCall cNameServ1ServiceNameIDTerminalRuleCall_3_0_1 = (RuleCall)cNameServ1ServiceNameCrossReference_3_0.eContents().get(1);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameCompAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cNameCompInstanceCompCrossReference_5_0 = (CrossReference)cNameCompAssignment_5.eContents().get(0);
		private final RuleCall cNameCompInstanceCompIDTerminalRuleCall_5_0_1 = (RuleCall)cNameCompInstanceCompCrossReference_5_0.eContents().get(1);
		private final Keyword cFullStopKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cNameServ2Assignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cNameServ2ServiceNameCrossReference_7_0 = (CrossReference)cNameServ2Assignment_7.eContents().get(0);
		private final RuleCall cNameServ2ServiceNameIDTerminalRuleCall_7_0_1 = (RuleCall)cNameServ2ServiceNameCrossReference_7_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Bindings:
		//	"bind(" nameComp+=[InstanceComp] '.' nameServ1+=[ServiceName] "," nameComp+=[InstanceComp] '.'
		//	nameServ2+=[ServiceName] ")";
		@Override public ParserRule getRule() { return rule; }
		
		//"bind(" nameComp+=[InstanceComp] '.' nameServ1+=[ServiceName] "," nameComp+=[InstanceComp] '.' nameServ2+=[ServiceName]
		//")"
		public Group getGroup() { return cGroup; }
		
		//"bind("
		public Keyword getBindKeyword_0() { return cBindKeyword_0; }
		
		//nameComp+=[InstanceComp]
		public Assignment getNameCompAssignment_1() { return cNameCompAssignment_1; }
		
		//[InstanceComp]
		public CrossReference getNameCompInstanceCompCrossReference_1_0() { return cNameCompInstanceCompCrossReference_1_0; }
		
		//ID
		public RuleCall getNameCompInstanceCompIDTerminalRuleCall_1_0_1() { return cNameCompInstanceCompIDTerminalRuleCall_1_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//nameServ1+=[ServiceName]
		public Assignment getNameServ1Assignment_3() { return cNameServ1Assignment_3; }
		
		//[ServiceName]
		public CrossReference getNameServ1ServiceNameCrossReference_3_0() { return cNameServ1ServiceNameCrossReference_3_0; }
		
		//ID
		public RuleCall getNameServ1ServiceNameIDTerminalRuleCall_3_0_1() { return cNameServ1ServiceNameIDTerminalRuleCall_3_0_1; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//nameComp+=[InstanceComp]
		public Assignment getNameCompAssignment_5() { return cNameCompAssignment_5; }
		
		//[InstanceComp]
		public CrossReference getNameCompInstanceCompCrossReference_5_0() { return cNameCompInstanceCompCrossReference_5_0; }
		
		//ID
		public RuleCall getNameCompInstanceCompIDTerminalRuleCall_5_0_1() { return cNameCompInstanceCompIDTerminalRuleCall_5_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_6() { return cFullStopKeyword_6; }
		
		//nameServ2+=[ServiceName]
		public Assignment getNameServ2Assignment_7() { return cNameServ2Assignment_7; }
		
		//[ServiceName]
		public CrossReference getNameServ2ServiceNameCrossReference_7_0() { return cNameServ2ServiceNameCrossReference_7_0; }
		
		//ID
		public RuleCall getNameServ2ServiceNameIDTerminalRuleCall_7_0_1() { return cNameServ2ServiceNameIDTerminalRuleCall_7_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
	}
	public class RequiredServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.RequiredService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameVarMethodeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameVarMethodeVariableParserRuleCall_0_0 = (RuleCall)cNameVarMethodeAssignment_0.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameCompAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cNameCompInstanceCompCrossReference_2_0 = (CrossReference)cNameCompAssignment_2.eContents().get(0);
		private final RuleCall cNameCompInstanceCompIDTerminalRuleCall_2_0_1 = (RuleCall)cNameCompInstanceCompCrossReference_2_0.eContents().get(1);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameServAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cNameServServiceNameCrossReference_4_0 = (CrossReference)cNameServAssignment_4.eContents().get(0);
		private final RuleCall cNameServServiceNameIDTerminalRuleCall_4_0_1 = (RuleCall)cNameServServiceNameCrossReference_4_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RequiredService:
		//	nameVarMethode+=Variable ":=" nameComp+=[InstanceComp] '.' nameServ+=[ServiceName] ";";
		@Override public ParserRule getRule() { return rule; }
		
		//nameVarMethode+=Variable ":=" nameComp+=[InstanceComp] '.' nameServ+=[ServiceName] ";"
		public Group getGroup() { return cGroup; }
		
		//nameVarMethode+=Variable
		public Assignment getNameVarMethodeAssignment_0() { return cNameVarMethodeAssignment_0; }
		
		//Variable
		public RuleCall getNameVarMethodeVariableParserRuleCall_0_0() { return cNameVarMethodeVariableParserRuleCall_0_0; }
		
		//":="
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//nameComp+=[InstanceComp]
		public Assignment getNameCompAssignment_2() { return cNameCompAssignment_2; }
		
		//[InstanceComp]
		public CrossReference getNameCompInstanceCompCrossReference_2_0() { return cNameCompInstanceCompCrossReference_2_0; }
		
		//ID
		public RuleCall getNameCompInstanceCompIDTerminalRuleCall_2_0_1() { return cNameCompInstanceCompIDTerminalRuleCall_2_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//nameServ+=[ServiceName]
		public Assignment getNameServAssignment_4() { return cNameServAssignment_4; }
		
		//[ServiceName]
		public CrossReference getNameServServiceNameCrossReference_4_0() { return cNameServServiceNameCrossReference_4_0; }
		
		//ID
		public RuleCall getNameServServiceNameIDTerminalRuleCall_4_0_1() { return cNameServServiceNameIDTerminalRuleCall_4_0_1; }
		
		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class ServiceNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.ServiceName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//ServiceName:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	
	public class TypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.aelos.xtext.mappingassistance.MappingAssistance.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINTINTKeyword_0_0 = (Keyword)cINTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSTRINGSTRINGKeyword_1_0 = (Keyword)cSTRINGEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBooleanBooleanKeyword_2_0 = (Keyword)cBooleanEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDoubleDoubleKeyword_3_0 = (Keyword)cDoubleEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Type:
		//	INT | STRING | Boolean | Double;
		public EnumRule getRule() { return rule; }
		
		//INT | STRING | Boolean | Double
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public EnumLiteralDeclaration getINTEnumLiteralDeclaration_0() { return cINTEnumLiteralDeclaration_0; }
		
		//"INT"
		public Keyword getINTINTKeyword_0_0() { return cINTINTKeyword_0_0; }
		
		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_1() { return cSTRINGEnumLiteralDeclaration_1; }
		
		//"STRING"
		public Keyword getSTRINGSTRINGKeyword_1_0() { return cSTRINGSTRINGKeyword_1_0; }
		
		//Boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_2() { return cBooleanEnumLiteralDeclaration_2; }
		
		//"Boolean"
		public Keyword getBooleanBooleanKeyword_2_0() { return cBooleanBooleanKeyword_2_0; }
		
		//Double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_3() { return cDoubleEnumLiteralDeclaration_3; }
		
		//"Double"
		public Keyword getDoubleDoubleKeyword_3_0() { return cDoubleDoubleKeyword_3_0; }
	}
	
	private final ModelElements pModel;
	private final AbstractModelElements pAbstractModel;
	private final ImportElements pImport;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final QualifiedNameElements pQualifiedName;
	private final ComponentElements pComponent;
	private final InstanceCompElements pInstanceComp;
	private final VariableElements pVariable;
	private final MappingElements pMapping;
	private final BindingsElements pBindings;
	private final RequiredServiceElements pRequiredService;
	private final ServiceNameElements pServiceName;
	private final TypeElements eType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MappingAssistanceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAbstractModel = new AbstractModelElements();
		this.pImport = new ImportElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pComponent = new ComponentElements();
		this.pInstanceComp = new InstanceCompElements();
		this.pVariable = new VariableElements();
		this.pMapping = new MappingElements();
		this.pBindings = new BindingsElements();
		this.pRequiredService = new RequiredServiceElements();
		this.pServiceName = new ServiceNameElements();
		this.eType = new TypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.aelos.xtext.mappingassistance.MappingAssistance".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	function+=AbstractModel*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//AbstractModel:
	//	Import comp+=Component+;
	public AbstractModelElements getAbstractModelAccess() {
		return pAbstractModel;
	}
	
	public ParserRule getAbstractModelRule() {
		return getAbstractModelAccess().getRule();
	}
	
	//Import:
	//	'import' importedNamespace=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//QualifiedNameWithWildcard:
	//	QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Component:
	//	("Component" | "Mock" | "Observator") ":"
	//	inst+=InstanceComp ":" name=ID
	//	"ProvidedServices:"
	//	"conf(" (arg+=Variable ",")* arg1+=Variable ")" (methode+=ServiceName "(" ((arg+=Variable ",")* arg+=Variable)* ")"
	//	(":" arg+=Variable)?)*
	//	"RequiredServices:"?
	//	req+=RequiredService*
	//	map+=Mapping*
	//	bind+=Bindings*;
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//InstanceComp:
	//	name=ID;
	public InstanceCompElements getInstanceCompAccess() {
		return pInstanceComp;
	}
	
	public ParserRule getInstanceCompRule() {
		return getInstanceCompAccess().getRule();
	}
	
	//Variable:
	//	name=ID ":" type=Type;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Mapping:
	//	'varModel:' nameVarMode+=[Variable] 'ref' 'varTest:' nameVarTest+=[testIntention::Variable];
	public MappingElements getMappingAccess() {
		return pMapping;
	}
	
	public ParserRule getMappingRule() {
		return getMappingAccess().getRule();
	}
	
	//Bindings:
	//	"bind(" nameComp+=[InstanceComp] '.' nameServ1+=[ServiceName] "," nameComp+=[InstanceComp] '.'
	//	nameServ2+=[ServiceName] ")";
	public BindingsElements getBindingsAccess() {
		return pBindings;
	}
	
	public ParserRule getBindingsRule() {
		return getBindingsAccess().getRule();
	}
	
	//RequiredService:
	//	nameVarMethode+=Variable ":=" nameComp+=[InstanceComp] '.' nameServ+=[ServiceName] ";";
	public RequiredServiceElements getRequiredServiceAccess() {
		return pRequiredService;
	}
	
	public ParserRule getRequiredServiceRule() {
		return getRequiredServiceAccess().getRule();
	}
	
	//ServiceName:
	//	name=ID;
	public ServiceNameElements getServiceNameAccess() {
		return pServiceName;
	}
	
	public ParserRule getServiceNameRule() {
		return getServiceNameAccess().getRule();
	}
	
	//enum Type:
	//	INT | STRING | Boolean | Double;
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
